// Furniture art, as char grids. Content is data (CLAUDE.md): a piece's
// SILHOUETTE is a row in this table, not a `case` in the renderer.
//
// The format and the reasoning are in `render/furnishings.ts`. In short: `.` is
// transparent, `k` is the shared outline ink, and `c` / `t` / `s` are not
// colours but questions — they resolve to the piece's finish (`color`, `top`,
// `shade`) when the grid is rasterized, so one grid serves all thirteen
// finishes. Any other char is a literal declared in the piece's own palette,
// which is how a brass lamp head stays brass in a walnut room.
//
// A grid is `w * TILE` wide and `rise + h * TILE + height` tall, and hangs from
// the anchor cell's top-left lifted by `height + rise`. That is exactly the box
// the old procedural path drew, plus `rise` — so a piece can move to art on its
// own, and anything without a row here keeps the box.
//
// AUTHORING NOTE, learned from the icons: draw the thing, not a shaded
// rectangle. What made the build-bar icons legible at 12px was legs, gaps and a
// visible back — negative space inside the footprint. A grid that fills its
// whole box is the box with extra steps.

import type { FurnitureId } from "./furniture";
import type { PieceArt } from "../render/furnishings";
import { INK } from "../render/furnishings";

/** Pieces drawn from art. Partial ON PURPOSE and permanently: `noticeboard` and
 *  `stage` are town fixtures whose procedural cases already say what they are,
 *  and the lamp leaves the generic path before this is ever consulted. A missing
 *  row is a piece that has not been converted, not a bug. */
export const FURNITURE_ART: Partial<Record<FurnitureId, PieceArt>> = {
  // A CHAIR IS THE TEST CASE, because it is the piece whose icon and whose world
  // drawing disagreed most. The icon has a back and four legs; the world had a
  // 16x30 block with a 3px band painted along its far edge, which is a chair
  // only if you already know it is one.
  //
  // Six of rise, and no more. `hides()` fades art that overhangs by more than
  // half a tile, and a chair that made the player see-through when they stood
  // behind it would be the occlusion machinery firing on the wrong furniture.
  // Six is enough for a back to read as standing over the seat rather than
  // painted on it, which is the whole job.
  chair: {
    rise: 6,
    mirrorW: true,
    s: {
      rows: [
        // The back, rising clear of the seat. Slatted rather than solid: two
        // gaps are what stop a 10x12 panel reading as a headboard, and they are
        // the same trick the icon uses at a third of the size.
        "...kkkkkkkkkk...",
        "...kttttttttk...",
        "...kcc.cc.cck...",
        "...kcc.cc.cck...",
        "...kcc.cc.cck...",
        "...kcc.cc.cck...",
        "...kcc.cc.cck...",
        "...kcc.cc.cck...",
        "...kcc.cc.cck...",
        "...kcc.cc.cck...",
        "...kssssssssk...",
        "...kkkkkkkkkk...",
        // The seat, seen from above and wider than the back.
        "..kkkkkkkkkkkk..",
        "..kttttttttttk..",
        "..kcccccccccck..",
        "..kcccccccccck..",
        "..kcccccccccck..",
        "..kcccccccccck..",
        "..kcccccccccck..",
        "..kcccccccccck..",
        "..kcccccccccck..",
        // Its near face — the thickness of the seat you look at edge-on.
        "..kssssssssssk..",
        "..kssssssssssk..",
        "..kssssssssssk..",
        "..kssssssssssk..",
        "..kkkkkkkkkkkk..",
        // Legs, and the floor showing between them. This is the part a box can
        // never have and the reason the whole module exists.
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kkk....kkk...",
      ],
      palette: { k: INK },
    },
    // Turned north — away from you — so you are looking at the BACK of the
    // back, standing at the near edge with the seat behind it. This is the one
    // facing that cannot fall through to `s`: the fallback puts the backrest at
    // the far edge, which is what a chair facing you looks like, so a chair
    // rotated to face away simply never changed. The six rows of `rise` go
    // unused here, because nothing on this view stands above the seat.
    n: {
      rows: [
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        // The seat, visible over the top of the backrest.
        "..kkkkkkkkkkkk..",
        "..kttttttttttk..",
        "..kcccccccccck..",
        "..kcccccccccck..",
        "..kcccccccccck..",
        "..kcccccccccck..",
        "..kcccccccccck..",
        "..kcccccccccck..",
        "..kcccccccccck..",
        "..kcccccccccck..",
        "..kcccccccccck..",
        "..kssssssssssk..",
        // The backrest, from behind and nearer the camera than the seat.
        "...kkkkkkkkkk...",
        "...kttttttttk...",
        "...kcc.cc.cck...",
        "...kcc.cc.cck...",
        "...kcc.cc.cck...",
        "...kcc.cc.cck...",
        "...kcc.cc.cck...",
        "...kcc.cc.cck...",
        "...kcc.cc.cck...",
        "...kcc.cc.cck...",
        "...kssssssssk...",
        "...kkkkkkkkkk...",
        // Short legs: the backrest hides most of them from this side.
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kkk....kkk...",
      ],
      palette: { k: INK },
    },
    // Turned east, the back is seen edge-on down the left side and the seat runs
    // away from it. Same rows, same box — a chair is 1x1 whichever way it faces,
    // so no dimension changes and `mirrorW` gets the west view for free.
    e: {
      rows: [
        "...kkkk.........",
        "...kttk.........",
        "...kcck.........",
        "...kcck.........",
        "...kcck.........",
        "...kcck.........",
        "...kcck.........",
        "...kcck.........",
        "...kcck.........",
        "...kcck.........",
        "...kssk.........",
        "...kkkk.........",
        "..kkkkkkkkkkkk..",
        "..kttttttttttk..",
        "..kcccccccccck..",
        "..kcccccccccck..",
        "..kcccccccccck..",
        "..kcccccccccck..",
        "..kcccccccccck..",
        "..kcccccccccck..",
        "..kcccccccccck..",
        "..kssssssssssk..",
        "..kssssssssssk..",
        "..kssssssssssk..",
        "..kssssssssssk..",
        "..kkkkkkkkkkkk..",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kkk....kkk...",
      ],
      palette: { k: INK },
    },
  },

  // A CUSHION had no case at all in the old switch — a bare 16x20 block four
  // pixels tall, which is a doorstep. Round, squashed, and dented in the middle,
  // because the one thing a cushion has to say is that it would give if you sat
  // on it.
  //
  // No facings. A cushion has no front, and authoring four identical grids to
  // say so would be four times the chance of them drifting apart.
  cushion: {
    s: {
      // Five blank rows first. The grid's top edge sits `height` above the tile
      // (4px for a cushion), so art written flush to row 0 lands a third of a
      // tile NORTH of the cell it was placed in — off by exactly the lift. The
      // blanks put it back in the middle of its own square.
      rows: [
        "................",
        "................",
        "................",
        "................",
        "................",
        "....kkkkkkkk....",
        "..kkttttttttkk..",
        ".kttccccccccttk.",
        "kttcccc..ccccttk",
        "ktcccc....cccctk",
        "kccccc....ccccck",
        "kcccccc..cccccck",
        "kcccccccccccccck",
        "kssssssssssssssk",
        ".kssssssssssssk.",
        "..kksssssssskk..",
        "....kkkkkkkk....",
        "................",
        "................",
        "................",
      ],
      palette: { k: INK },
    },
  },

  // A chair with the back taken off, and drawn as exactly that: the same
  // seat and legs, nine pixels lower and rounder. If it read as tall as a chair it
  // would just be a chair drawn worse.
  stool: {
    s: {
      rows: [
        "................",
        "................",
        "...kkkkkkkkkk...",
        "..kttttttttttk..",
        ".kttttttttttttk.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        "..kssssssssssk..",
        "..kkkkkkkkkkkk..",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kkk....kkk...",
      ],
      palette: { k: INK },
    },
  },

  // A seat with a rail behind it on posts, which is what stops it being a
  // long stool. Turned east the rail is seen edge-on down one side.
  bench: {
    rise: 4,
    mirrorW: true,
    s: {
      rows: [
        "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
        "..kttttttttttttttttttttttttttk..",
        "..kcccccccccccccccccccccccccck..",
        "..kcccccccccccccccccccccccccck..",
        "..kcccccccccccccccccccccccccck..",
        "..kcccccccccccccccccccccccccck..",
        "..kcccccccccccccccccccccccccck..",
        "..kssssssssssssssssssssssssssk..",
        "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        ".kttttttttttttttttttttttttttttk.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kkk....................kkk...",
      ],
      palette: { k: INK },
    },
    n: {
      rows: [
        "................................",
        "................................",
        "................................",
        "................................",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        ".kttttttttttttttttttttttttttttk.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
        "..kttttttttttttttttttttttttttk..",
        "..kcccccccccccccccccccccccccck..",
        "..kcccccccccccccccccccccccccck..",
        "..kcccccccccccccccccccccccccck..",
        "..kcccccccccccccccccccccccccck..",
        "..kcccccccccccccccccccccccccck..",
        "..kssssssssssssssssssssssssssk..",
        "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kkk....................kkk...",
      ],
      palette: { k: INK },
    },
    e: {
      rows: [
        "..kkkk..........",
        "..kcck..........",
        "..kcck..........",
        "..kcck..........",
        "..kcck..........",
        "..kcck..........",
        "..kcck..........",
        "..kcck..........",
        "..kkkk..........",
        ".kkkkkkkkkkkkkk.",
        ".kttttttttttttk.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kkkkkkkkkkkkkk.",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kkk....kkk...",
      ],
      palette: { k: INK },
    },
  },

  // Arms at both ends, a back with a lit top roll, and two seat cushions with
  // a gap between them. The frame and feet are LITERAL timber while the upholstery
  // takes the finish, because a sofa is genuinely two materials and you only choose one.
  sofa: {
    rise: 4,
    mirrorW: true,
    s: {
      rows: [
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        ".kttttttttttttttttttttttttttttk.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kssssssssssssssssssssssssssssk.",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        ".kccckcccccccccckccccccccckccck.",
        ".kccckcccccccccckccccccccckccck.",
        ".kccckcccccccccckccccccccckccck.",
        ".kccckcccccccccckccccccccckccck.",
        ".kccckcccccccccckccccccccckccck.",
        ".kccckcccccccccckccccccccckccck.",
        ".kccckcccccccccckccccccccckccck.",
        ".kccckcccccccccckccccccccckccck.",
        ".kccckcccccccccckccccccccckccck.",
        ".kccckcccccccccckccccccccckccck.",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        "...kkk....................kkk...",
      ],
      palette: { k: INK, w: "#a87c4a" },
    },
    n: {
      rows: [
        "................................",
        "................................",
        "................................",
        "................................",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        ".kccckcccccccccckccccccccckccck.",
        ".kccckcccccccccckccccccccckccck.",
        ".kccckcccccccccckccccccccckccck.",
        ".kccckcccccccccckccccccccckccck.",
        ".kccckcccccccccckccccccccckccck.",
        ".kccckcccccccccckccccccccckccck.",
        ".kccckcccccccccckccccccccckccck.",
        ".kccckcccccccccckccccccccckccck.",
        ".kccckcccccccccckccccccccckccck.",
        ".kccckcccccccccckccccccccckccck.",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        ".kttttttttttttttttttttttttttttk.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kssssssssssssssssssssssssssssk.",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        "...kkk....................kkk...",
      ],
      palette: { k: INK, w: "#a87c4a" },
    },
    e: {
      rows: [
        ".kkkkk..........",
        ".kccck..........",
        ".kccck..........",
        ".kccck..........",
        ".kccck..........",
        ".kccck..........",
        ".kccck..........",
        ".kccck..........",
        ".kccck..........",
        ".kccck..........",
        ".kccck..........",
        ".kccck..........",
        ".kccck..........",
        ".kkkkk..........",
        "kkkkkkkkkkkkkkkk",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kcccccccccccccck",
        "kkkkkkkkkkkkkkkk",
        "kssssssssssssssk",
        "kssssssssssssssk",
        "kssssssssssssssk",
        "kssssssssssssssk",
        "kssssssssssssssk",
        "kssssssssssssssk",
        "kssssssssssssssk",
        "kssssssssssssssk",
        "kkkkkkkkkkkkkkkk",
        "...kkk....kkk...",
      ],
      palette: { k: INK, w: "#a87c4a" },
    },
  },

  // The table, seven pixels lower. Nothing else changes, and nothing
  // else should: it is the same object at the height that makes it a different one.
  coffeetable: {
    mirrorW: true,
    s: {
      rows: [
        "................................",
        "................................",
        "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
        ".kttttttttttttttttttttttttttttk.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kkk....................kkk...",
      ],
      palette: { k: INK },
    },
    e: {
      rows: [
        "................",
        "................",
        "..kkkkkkkkkkkk..",
        ".kttttttttttttk.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kkkkkkkkkkkkkk.",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kkk....kkk...",
      ],
      palette: { k: INK },
    },
  },

  // A tabletop with a drawer pedestal under its right half and a KNEEHOLE
  // under the left. That asymmetry is the entire silhouette difference from a table,
  // and it is the reason a desk is worth being its own row.
  desk: {
    mirrorW: true,
    s: {
      rows: [
        "................................",
        "................................",
        "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
        ".kttttttttttttttttttttttttttttk.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        "...............kkkkkkkkkkkkkk...",
        "...............kcccccccccccck...",
        "...............kcccccccccccck...",
        "...............kcccccccccccck...",
        "...............kccccdddccccck...",
        "...............kcccccccccccck...",
        "...............kcccccccccccck...",
        "...............kkkkkkkkkkkkkk...",
        "...............kcccccccccccck...",
        "...............kcccccccccccck...",
        "...............kcccccccccccck...",
        "...kck.........kkkkkkkkkkkkkk...",
        "...kkk....................kkk...",
      ],
      palette: { k: INK, d: "#9c7a2c" },
    },
    e: {
      rows: [
        "................",
        "................",
        "..kkkkkkkkkkkk..",
        ".kttttttttttttk.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kkkkkkkkkkkkkk.",
        ".kcccccccccccck.",
        "..kccccddcccck..",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kkkkkkkkkkkkkk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kkkkkkkkkkkkkk.",
        "...kk......kk...",
      ],
      palette: { k: INK, d: "#9c7a2c" },
    },
  },

  // Two drawers and stubby feet. Small enough that the feet matter:
  // without them it is a block, and a block beside a bed is a crate.
  nightstand: {
    s: {
      rows: [
        "................",
        "................",
        "................",
        ".kkkkkkkkkkkkkk.",
        ".kttttttttttttk.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kssssssssssssk.",
        ".kkkkkkkkkkkkkk.",
        ".kcccccccccccck.",
        "..kccccddcccck..",
        ".kcccccccccccck.",
        ".kkkkkkkkkkkkkk.",
        ".kcccccccccccck.",
        "..kccccddcccck..",
        ".kcccccccccccck.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kkkkkkkkkkkkkk.",
        "...kk......kk...",
        "...kk......kk...",
        "...kk......kk...",
        "...kk......kk...",
      ],
      palette: { k: INK, d: "#9c7a2c" },
    },
  },

  // Canvas slung in a frame at shin height. Flat, thin and cheap-looking on
  // purpose — it should read as the thing you put in a room you only just walled in.
  cot: {
    mirrorW: true,
    s: {
      rows: [
        ".kkkkkkkkkkkkkk.",
        ".kwwwwwwwwwwwwk.",
        ".kkkkkkkkkkkkkk.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kkkkkkkkkkkkkk.",
        ".kwwwwwwwwwwwwk.",
        ".kkkkkkkkkkkkkk.",
        "..kk........kk..",
        "..kk........kk..",
        "..kk........kk..",
        "..kk........kk..",
      ],
      palette: { k: INK, w: "#a87c4a" },
    },
    e: {
      rows: [
        "................................",
        "................................",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        "...kwk....................kwk...",
        "...kwk....................kwk...",
        "...kwk....................kwk...",
        "...kwk....................kwk...",
        "...kkk....................kkk...",
      ],
      palette: { k: INK, w: "#a87c4a" },
    },
  },

  // The tallest thing you can put in a room, so it gets a CORNICE — the
  // four rows of overhang the `rise` buys. A tall box with a lid reads as furniture;
  // a tall box does not. Two doors, a centre stile, two knobs.
  wardrobe: {
    rise: 6,
    s: {
      rows: [
        "kkkkkkkkkkkkkkkk",
        "kttttttttttttttk",
        "kcccccccccccccck",
        "kkkkkkkkkkkkkkkk",
        ".kkkkkkkkkkkkkk.",
        ".kttttttttttttk.",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccdkkdccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        "..kcccckkcccck..",
        ".kssssssssssssk.",
        ".kkkkkkkkkkkkkk.",
        "...kk......kk...",
        "...kk......kk...",
        "...kk......kk...",
        "...kk......kk...",
      ],
      palette: { k: INK, d: "#9c7a2c" },
    },
  },

  // Curved lid, hard rim, one brass clasp. The rim is the whole trick —
  // it is what says lid rather than box, and it costs one row.
  chest: {
    s: {
      rows: [
        "................",
        "................",
        "................",
        "..kkkkkkkkkkkk..",
        ".kttttttttttttk.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kkkkkkkkkkkkkk.",
        ".kssssssssssssk.",
        ".kcccccccccccck.",
        "..kccccbbcccck..",
        "..kccccbbcccck..",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kkkkkkkkkkkkkk.",
      ],
      palette: { k: INK, b: "#9c7a2c" },
    },
  },

  // Three drawers, six pulls, stubby feet. Reads against the desk by
  // being solid all the way down — no kneehole, no gap.
  dresser: {
    mirrorW: true,
    s: {
      rows: [
        "................................",
        "................................",
        "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
        ".kttttttttttttttttttttttttttttk.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kssssssssssssssssssssssssssssk.",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        ".kcccccccccccccccccccccccccccck.",
        "..kccccccdddccccccccdddcccccck..",
        ".kcccccccccccccccccccccccccccck.",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        ".kcccccccccccccccccccccccccccck.",
        "..kccccccdddccccccccdddcccccck..",
        ".kcccccccccccccccccccccccccccck.",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        ".kcccccccccccccccccccccccccccck.",
        "..kccccccdddccccccccdddcccccck..",
        ".kcccccccccccccccccccccccccccck.",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        "...kk......................kk...",
        "...kk......................kk...",
        "...kk......................kk...",
        "...kk......................kk...",
      ],
      palette: { k: INK, d: "#9c7a2c" },
    },
    e: {
      rows: [
        "................",
        "................",
        "..kkkkkkkkkkkk..",
        ".kttttttttttttk.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kssssssssssssk.",
        ".kkkkkkkkkkkkkk.",
        ".kcccccccccccck.",
        "..kccccddcccck..",
        ".kcccccccccccck.",
        ".kkkkkkkkkkkkkk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kkkkkkkkkkkkkk.",
        "...kk......kk...",
      ],
      palette: { k: INK, d: "#9c7a2c" },
    },
  },

  // Mostly empty grid, and deliberately: the art box is as tall as the
  // tile is deep, and a small object should sit in the bottom of it rather than being
  // stretched to fill it. Brass shade over a lit throat, a thin post, a round foot.
  desklamp: {
    rise: 6,
    s: {
      rows: [
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "...kkkkkkkkkk...",
        "...kbbbbbbbbk...",
        "..kbbbbbbbbbbk..",
        "..kffffffffffk..",
        "..kkkkkkkkkkkk..",
        "......kck.......",
        "......kck.......",
        "......kck.......",
        "......kck.......",
        "......kck.......",
        "......kck.......",
        "......kck.......",
        "......kck.......",
        "......kck.......",
        "...kkkkkkkkkk...",
        "...kttttttttk...",
        "...kcccccccck...",
        "...kssssssssk...",
        "...kkkkkkkkkk...",
        "................",
      ],
      palette: { k: INK, b: "#9c7a2c", f: "#ffcf7a" },
    },
  },

  // Rounded top, four legs, and the floor visible between them. The old
  // procedural table was this outline with no legs at all, which is a plinth.
  table: {
    mirrorW: true,
    s: {
      rows: [
        "................................",
        "................................",
        "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
        ".kttttttttttttttttttttttttttttk.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kcccccccccccccccccccccccccccck.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kck....................kck...",
        "...kkk....................kkk...",
      ],
      palette: { k: INK },
    },
    e: {
      rows: [
        "................",
        "................",
        "..kkkkkkkkkkkk..",
        ".kttttttttttttk.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kkkkkkkkkkkkkk.",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kck....kck...",
        "...kkk....kkk...",
      ],
      palette: { k: INK },
    },
  },

  // Three shelves of books in four spine colours, which are LITERALS — a
  // bookcase repainted walnut should not repaint its books. That is the same division
  // the lamp makes about brass.
  shelf: {
    rise: 4,
    s: {
      rows: [
        ".kkkkkkkkkkkkkk.",
        ".kttttttttttttk.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kkkkkkkkkkkkkk.",
        "..krrgggyypppk..",
        "..krrgggyypppk..",
        "..krrgggyypppk..",
        "..krrgggyypppk..",
        "..krrgggyypppk..",
        "..krrgggyypppk..",
        ".kkkkkkkkkkkkkk.",
        "..kppyyyrrgggk..",
        "..kppyyyrrgggk..",
        "..kppyyyrrgggk..",
        "..kppyyyrrgggk..",
        "..kppyyyrrgggk..",
        "..kppyyyrrgggk..",
        ".kkkkkkkkkkkkkk.",
        "..kggrrrppyyyk..",
        "..kggrrrppyyyk..",
        "..kggrrrppyyyk..",
        "..kggrrrppyyyk..",
        "..kggrrrppyyyk..",
        "..kggrrrppyyyk..",
        ".kkkkkkkkkkkkkk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kssssssssssssk.",
        ".kkkkkkkkkkkkkk.",
        "...kk......kk...",
        "...kk......kk...",
        "...kk......kk...",
      ],
      palette: { k: INK, r: "#b8563c", g: "#5e8c4a", y: "#d9b04a", p: "#7a6aa8" },
    },
  },

  // Pillow, blanket, headboard, footboard — the blanket and pillow literal, the
  // frame taking the wood finish. Authored all three ways round: a bed is the piece
  // whose head end matters most, and `n` swaps the pillow to the near end.
  bed: {
    mirrorW: true,
    s: {
      rows: [
        ".kkkkkkkkkkkkkk.",
        ".kttttttttttttk.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kkkkkkkkkkkkkk.",
        ".kppppppppppppk.",
        ".kppppppppppppk.",
        ".kppppppppppppk.",
        ".kppppppppppppk.",
        ".kppppppppppppk.",
        ".kppppppppppppk.",
        ".kkkkkkkkkkkkkk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kkkkkkkkkkkkkk.",
        ".kssssssssssssk.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kkkkkkkkkkkkkk.",
        "..kk........kk..",
        "..kk........kk..",
        "..kk........kk..",
        "..kk........kk..",
        "..kk........kk..",
      ],
      palette: { k: INK, p: "#f2ece0", q: "#6a8fc0" },
    },
    n: {
      rows: [
        ".kkkkkkkkkkkkkk.",
        ".kssssssssssssk.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kkkkkkkkkkkkkk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kqqqqqqqqqqqqk.",
        ".kppppppppppppk.",
        ".kppppppppppppk.",
        ".kppppppppppppk.",
        ".kppppppppppppk.",
        ".kppppppppppppk.",
        ".kppppppppppppk.",
        ".kkkkkkkkkkkkkk.",
        ".kkkkkkkkkkkkkk.",
        ".kttttttttttttk.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kkkkkkkkkkkkkk.",
        "..kk........kk..",
        "..kk........kk..",
        "..kk........kk..",
        "..kk........kk..",
        "..kk........kk..",
      ],
      palette: { k: INK, p: "#f2ece0", q: "#6a8fc0" },
    },
    e: {
      rows: [
        "................................",
        "................................",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        ".kcckpppppppkqqqqqqqqqqqqqqqk...",
        ".kcckpppppppkqqqqqqqqqqqqqqqk...",
        ".kcckpppppppkqqqqqqqqqqqqqqqk...",
        ".kcckpppppppkqqqqqqqqqqqqqqqk...",
        ".kcckpppppppkqqqqqqqqqqqqqqqk...",
        ".kcckpppppppkqqqqqqqqqqqqqqqk...",
        ".kcckpppppppkqqqqqqqqqqqqqqqk...",
        ".kcckpppppppkqqqqqqqqqqqqqqqk...",
        ".kcckpppppppkqqqqqqqqqqqqqqqk...",
        ".kcckpppppppkqqqqqqqqqqqqqqqk...",
        ".kcckpppppppkqqqqqqqqqqqqqqqk...",
        ".kcckpppppppkqqqqqqqqqqqqqqqk...",
        ".kcckpppppppkqqqqqqqqqqqqqqqk...",
        ".kcckpppppppkqqqqqqqqqqqqqqqk...",
        ".kcckpppppppkqqqqqqqqqqqqqqqk...",
        ".kcckpppppppkqqqqqqqqqqqqqqqk...",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        ".kssssssssssssssssssssssssssssk.",
        "...kkk....................kkk...",
      ],
      palette: { k: INK, p: "#f2ece0", q: "#6a8fc0" },
    },
  },

  // Border, centre motif, and a FRINGE along the bottom edge. One grid for
  // every facing, because a rug has no front — and the fringe is what stops a 2x2 of
  // flat colour reading as a stain on the floor.
  rug: {
    s: {
      rows: [
        "................................",
        "................................",
        "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
        "..kttttttttttttttttttttttttttk..",
        "..kttccccccccccccccccccccccttk..",
        "..kttccccccccccccccccccccccttk..",
        "..kttccccccccccccccccccccccttk..",
        "..kttccccccccccccccccccccccttk..",
        "..kttccccccccccccccccccccccttk..",
        "..kttccccccccccccccccccccccttk..",
        "..kttccccccccccccccccccccccttk..",
        "..kttccccssssssssssssssccccttk..",
        "..kttccccssssssssssssssccccttk..",
        "..kttccccssssssssssssssccccttk..",
        "..kttccccssssssssssssssccccttk..",
        "..kttccccssssssssssssssccccttk..",
        "..kttccccssssssssssssssccccttk..",
        "..kttccccssssssssssssssccccttk..",
        "..kttccccssssssssssssssccccttk..",
        "..kttccccssssssssssssssccccttk..",
        "..kttccccssssssssssssssccccttk..",
        "..kttccccssssssssssssssccccttk..",
        "..kttccccccccccccccccccccccttk..",
        "..kttccccccccccccccccccccccttk..",
        "..kttccccccccccccccccccccccttk..",
        "..kttccccccccccccccccccccccttk..",
        "..kttccccccccccccccccccccccttk..",
        "..kttccccccccccccccccccccccttk..",
        "..kttccccccccccccccccccccccttk..",
        "..kttttttttttttttttttttttttttk..",
        "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
        "..k.k.k.k.k.k.k.k.k.k.k.k.k.k...",
        "..k.k.k.k.k.k.k.k.k.k.k.k.k.k...",
      ],
      palette: { k: INK },
    },
  },

  // A PAINTING IS THE ONE PIECE THAT HANGS. Its grid is `w * TILE` by `height`
  // and nothing else — no footprint to lift and no near face, because it never
  // touches a floor. Frame in the finish, picture in literals: a walnut frame
  // should not repaint the hills inside it, which is the bookshelf's rule about
  // its own books and the lamp's about its brass.
  painting: {
    s: {
      rows: [
        ".kkkkkkkkkkkkkk.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kccaaaaaaaacck.",
        ".kccaaaaaaaacck.",
        ".kccaaaammaacck.",
        ".kccaammbbmacck.",
        ".kccambbbbbmcck.",
        ".kccbbbbbbbbcck.",
        ".kccbbbbbbbbcck.",
        ".kcccccccccccck.",
        ".kcccccccccccck.",
        ".kkkkkkkkkkkkkk.",
        "..dddddddddddd..",
      ],
      palette: { k: INK, a: "#a8cfe8", m: "#8fb87a", b: "#6f9e5c", d: "rgba(0,0,0,0.20)" },
    },
  },
};
